on:
  push:
    branches:
      - master
name: Deploy master branch
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@master
      with:
        root_file: pole-stars.tex
        args: -xelatex -file-line-error -interaction=nonstopmode -halt-on-error
    - uses: actions/upload-artifact@v1
      with:
        name: game-pdf
        path: pole-stars.pdf